#!/usr/bin/env bash
# Displays To infinity and beyond indefinitely & sleep 2 between each iteration

trap 'echo "I am invincible!!!"' SIGTERM
while true
do
    echo "To infinity and beyond"
    sleep 2
done
