#!/usr/bin/env bash
# Script displays the username, user id, and home directory path
# from the /etc/passwd file using a while loop.

while IFS=':' read -r login _ uid _ _ home _
do
    printf '%s:%s:%s\n' "${login}" "${uid}" "${home}"
done </etc/passwd
