#!/usr/bin/env bash
# Script displays information about users from the /etc/passwd file
# using a while loop and the IFS variable.

storytime()
{
    cat
} <<@STOP
The user $1 is part of the $4 gang, lives in $6 and rides $7. $3's place is \
protected by the passcode $2, more info about the user here: $5
@STOP

while IFS=':' read -ra account
do
    storytime "${account[@]}"
done </etc/passwd
