#!/usr/bin/env bash
# This script displays "Best School" 10 times, for 9th iteration, it also displays "Hi"

i=0
while (( i++ < 10 ))
do
    echo 'Best School'
    if (( i == 9 ))
    then
        echo 'Hi'
    fi
done
