#!/usr/bin/env bash

# Script loops from 1 to 10 and displays different messages based on the iteration

i=0
while (( i++ < 10 ))
do
    if (( i == 4 ))
    then
        echo 'bad luck'
    elif (( i == 8 ))
    then
        echo 'good luck'
    else
        echo 'Best School'
    fi
done
